### ISSUE TITLE
Post Taxonomy placeholder suddenly disapears

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#826] opened 2023-11-18 17:16 UTC
### Description

When I open the Map Content accordion, the Post Taxonomy placeholder, "Select Some Options" disappears.

### Step-by-step reproduction instructions

1. Go to Feedzy > Import
2. Create a new import
3. Open the Map content accordion
4. Notice the Post Taxonomy dropdown behavior

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/GhUkC3

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment] 2023-11-21 07:57
@girishpanchal30 Tested and the issue is fixed now, thank you 👍

**Closed** 2023-12-22 15:22 UTC
Labels: bug, released
