### ISSUE TITLE
WordPress categories are not imported with the Feedzy import since version 4.3.3

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#866] opened 2024-01-29 17:52 UTC
### Description

It was reported that when using [#item_categories] or [#item_custom_x] (some custom tag parsing) in the Feedzy Import Settings as taxonomy a category is not created in WordPress.

I was able to replicate this issue, during my tests I found out that this issue happened with version 4.3.3 of the Free version of the plugin. 
This feature was introduced with 4.3.0 version - https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/569
It still works with version 4.3.1 and 4.3.2 but stops working with 4.3.3: https://github.com/Codeinwp/feedzy-rss-feeds/releases/tag/v4.3.3

You can replicate this with any feed that, I was testing with this: https://it.cryptonews.com/news/feed/

Using [#item_categories]:
<img width="1218" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/36594177/ca8ae820-875b-4fce-803a-5827cbea5c8b">

With free Feedzy downgraded to 4.3.2 items are imported with categories:
<img width="254" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/36594177/472f3985-1fb9-4602-8a4f-a16e80eaa23f">

With 4.3.3+ no category is imported:
<img width="153" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/36594177/2f63a22d-19f5-4fb2-956d-08be54dcf268">

Even if you add a hardcoded value (anything) as Taxonomy to be assigned, that hardcoded value is not created as a taxonomy in WordPress during the import and items are not assigned to it.

### Step-by-step reproduction instructions

1. Create a new import and try to use Taxonomy field to create category in WordPress during the import.
2. Run the import
3. Check if items imported have any category assigned (harcoded or the one from a magic tag depending on what you added).

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment] 2024-01-30 05:49
Hey @vytisbulkevicius,

I've reviewed this issue and fixed it with this PR https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/672

Thanks

**Comment by irinelenache** [comment] 2024-01-31 14:20
@girishpanchal30 Tested and the issue is fixed now 👍

**Closed** 2024-02-02 11:45 UTC
Labels: bug, Priority-Medium
