### ISSUE TITLE
Conflict with Advanced Custom Fields due to a nonce being checked in Feedzy

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/feedzy-rss-feeds#747] opened 2023-04-11 13:53 UTC
### Description

When the plugin is active on a site with ACF, form submission of ACF generates an error because of [this](https://github.com/Codeinwp/feedzy-rss-feeds/blob/92d394010b93f35e0c2ac90928d5587b88531631/includes/admin/feedzy-rss-feeds-import.php#L1963) line in Feedzy.

If the `tab` within this code sippet doesn't exist, it interferes with the functionality of Advanced Custom Fields.

### Step-by-step reproduction instructions

https://www.loom.com/share/79d97bd5a74f4a6d8b819d0018359a92

### Screenshots, screen recording, code snippet or Help Scout ticket

I'll ask for the site health also.

Reported here: https://secure.helpscout.net/conversation/2209976005/365414?folderId=931544

### Environment info

https://pastebin.com/WjjMNYQW

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment] 2023-04-12 10:16
@stefan-cotitosu Can you please check if the issue is fixed on the user's website 🙏 ? I didn't manage to replicate the issue because i don't have access to the plugins used to create the form

**Comment by stefan-cotitosu** [comment] 2023-04-12 11:00
Sure, I'll share the build with the user so he can confirm, since it's third-party compatibility. Thanks!

**Comment by irinelenache** [comment] 2023-04-18 12:49
@stefan-cotitosu Feel free to move this to **Ready to merge** if the fix is confirmed 🚀

**Closed** 2023-05-01 14:50 UTC
Labels: bug, 3rd-part-compatibilities, customer report
