### ISSUE TITLE
Images Not Displaying for some Posts when using Feedzy block

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/feedzy-rss-feeds#768] opened 2023-06-08 21:35 UTC
### Description

A Customer has reported that images are not being displayed for certain posts when utilizing the Feedzy plugin's Elementor Feedzy block option. As an example, the user provided the following feeds: https://info.lynden.com/blog/topic/alaska/rss.xml and https://info.lynden.com/blog/topic/drivers/rss.xml

I have checked the feed on the SimplePie website and confirmed that the image appears for the first post as shown here - https://vertis.d.pr/i/TqCNo1

However, when using Feedzy to display the feed posts, the images are not present on my [instance ](https://kush.stefancoti.com/index.php/2023/06/08/test/)- https://vertis.d.pr/i/Wr76V4

I have noticed one thing the posts have images linked in the form of CSS https://vertis.d.pr/i/G6m1eo but when you inspect the image element of the post having no image, the image URL is incomplete as shown here - https://vertis.d.pr/i/FCvC56

Although the `amp-img` element contains the correct image URL.

### Step-by-step reproduction instructions

1. Install and activate the Feedzy plugin.
2. Access the Elementor editor.
3. Add the Feedzy block to a page or post.
4. Configure the Feedzy block to display the provided RSS feed: https://info.lynden.com/blog/topic/alaska/rss.xml.
5. Preview or publish the page/post with the Feedzy block.
6. Observe that the displayed posts from the feed do not contain images.

### Screenshots, screen recording, code snippet or Help Scout ticket

![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/110405452/e29df513-25ba-4f4f-a6d7-df305cf4303a)
![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/110405452/6827798c-9648-4063-946b-bde4fa17ea0f)
![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/110405452/b0271b7a-188e-4cf1-9b17-98f99bca590d)

![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/110405452/6cb288eb-9c93-4ed0-9d9f-a048499621d2)

Test page: https://kush.stefancoti.com/index.php/2023/06/08/test/
HS - https://secure.helpscout.net/conversation/2265543698/372245/

### Is the issue you are reporting a regression

No

**Comment by kushh23** [comment] 2023-06-08 21:37
I tested it with a normal Gutenberg editor using feedzy block and the issue is the same irrespective of Elementor - https://kush.stefancoti.com/index.php/2023/06/08/test-2/

**Comment by girishpanchal30** [comment] 2023-06-12 07:06
Hey @kushh23,

I can't replicate this issue, Could you please share your test instance details here?
Ref: https://feedzy-768.s4-tastewp.com/2023/06/12/768/, https://tinyurl.com/24v94ow2

Thanks

**Comment by kushh23** [comment] 2023-06-12 07:24
Hey @girishpanchal30 

I rechecked this behavior on a new test instance but could not replicate it there. But on the further check, I found that this behavior is replicable. with the feedzy pro plugin. 

Here are the details - 

Site name: Doubt Polish
URL: https://doubtpolish.s4-tastewp.com
Username: kushnamdev
Password: jShcpzKfQwc

test page : https://doubtpolish.s4-tastewp.com/2023/06/12/elementor-21/

**Comment by girishpanchal30** [comment] 2023-06-12 12:20
Hey @kushh23,

I've reviewed this issue and found the problem with escaping the image tag in the PRO version template.
So the issue is fixed with this PR https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/587

Also, I've found another image-loading issue in the Gutenberg block and it is fixed in this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/770
Please check with the attached PR and do let me know if you have any issues.

Thanks

**Comment by irinelenache** [comment] 2023-06-12 14:53
@girishpanchal30 Tested and the images work fine now, both in Gutenberg and Elementor 👍

**Closed** 2023-07-06 08:07 UTC
Labels: bug, customer report
