### ISSUE TITLE
[feed2post] Number of Items imported across runs does not count duplicates

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/feedzy-rss-feeds#463] opened 2020-08-11 17:50 UTC
with the new `Purge & Reset` option you quickly run the same import multiple times which will import some of the posts multiple time.
But this doesn't reflect in the `Number of Items imported across runs` option.

For example, here I've run the same import twice, which got 20 posts imported in total.
![1](https://user-images.githubusercontent.com/3266155/89930975-38e1cc00-dc14-11ea-9a15-0e11c48dd0f0.png)

But the Number of Items imported across runs remains 10.
![2](https://user-images.githubusercontent.com/3266155/89931020-4bf49c00-dc14-11ea-8cab-c7737a61575f.png)

**Comment by contactashish13** [comment] 2020-08-17 12:56
@rodica-andronache can you please mention the steps to follow here?

**Comment by rodica-andronache** [comment] 2020-08-17 16:01
@contactashish13 made a video, hope it's more useful https://www.loom.com/share/14080f98433d427886b8caeb28608828

**Comment by contactashish13** [comment] 2020-08-18 08:17
@rodica-andronache yes because purge is for purging our data not the posts that were imported. So this confusion will remain if the user has not delete the posts. I'm not sure what is the expected behavior

**Comment by contactashish13** [comment] 2020-08-27 13:49
@rodica-andronache here is where I had responded. Let me know if you expect a different behavior from what has been defined.

**Comment by contactashish13** [comment] 2020-09-29 07:14
@rodica-andronache please close this if this is not a bug but if it is, can you explain the behavior you expect wrt to the user's expectation?

**Closed** 2020-10-14 11:20 UTC
Labels: bug
