### ISSUE TITLE
Featured image is not assigned to imported posts if URL of image is used instead of [#item_image] tag

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#755] opened 2023-04-20 13:06 UTC
### Description

Starting with version 4.2.2 - https://github.com/Codeinwp/feedzy-rss-feeds/releases/tag/v4.2.2

Featured image is not imported for posts if you use URL for the featured image:
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/36594177/233374474-d288e2fc-ee3e-4079-b86d-4d598c282c8d.png">
And a tag.

Also, user reported this happening with image assigned in Settings->General section where we can also assign image instead of taking it from the RSS XML Feed.

I assume this issue could be related to the solution that was used to fix "Multiple attachments generating issue".

Rolling back Free plugin to 4.2.1 version fixes the issue.

### Step-by-step reproduction instructions

1. Create an import and to import featured images use URL of image instead of [#item_image] or another tag.
2. Run the import and see that featured images are not imported for items.
3. Rollback to Feedzy free 4.2.1 and try again, image is there for imported posts as a featured image.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2203822310/364407

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by girishpanchal30** [comment] 2023-04-20 13:42
Hey @vytisbulkevicius,

I've reviewed this issue and fixed it with this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/756, please check with the build zip, and do let me know if you have any issues.

Thanks

**Comment by irinelenache** [comment] 2023-04-21 09:44
@girishpanchal30 Tested and the issue is fixed now 🚀

**Comment by vytisbulkevicius** [comment] 2023-04-24 07:15
Hi @girishpanchal30,

This PR fixes the issue mentioned but I'm a little confused about how to use it combined with other fixes.

So this PR - https://github.com/Codeinwp/feedzy-rss-feeds/pull/756
has changes in the same file as https://github.com/Codeinwp/feedzy-rss-feeds/pull/751

So if I use PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/756 it again has issues with duplicates/CRON not running imports. Can you confirm?

Also, all these issues were introduced with plugin's update to version 4.2.2, I just thought that it would be good to analyse what was changed there that caused these issues and potentially address such issues from focusing on what error was made there instead of fixing it from the point that it's a new problem (not sure about the approach you're taking, that's just how I'm thinking of it). 

As we recently had many regressions with that Feedzy release and it has a very bad impact on the customers.

Can we also have unit tests for all those issues fixed to prevent them in the future?
https://github.com/Codeinwp/feedzy-rss-feeds/issues/750
https://github.com/Codeinwp/feedzy-rss-feeds/issues/749
https://github.com/Codeinwp/feedzy-rss-feeds/issues/743
And this one I'm commenting on - https://github.com/Codeinwp/feedzy-rss-feeds/issues/755

Thank you!

**Closed** 2023-05-01 14:50 UTC
Labels: bug, regression, customer report
