### ISSUE TITLE
Typo on the Help page

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/feedzy-rss-feeds#823] opened 2023-11-10 17:15 UTC
### Description

This was also reported in Metabase this week: **Gettting Started is spelt incorrect**

<img width="1621" alt="Screenshot 2023-11-10 at 19 14 04" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/52494172/8036ab60-1d67-4898-bed3-ddeb93f4e4ad">

### Step-by-step reproduction instructions

1. Create a clean instance
2. Add Feedzy Free 4.3.2
3. Go to the Support page
4. Notice the Tab title

### Screenshots, screen recording, code snippet or Help Scout ticket

Attached above.

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment] 2023-11-16 10:02
@girishpanchal30 The issue is fixed now 👍

**Closed** 2023-12-22 15:17 UTC
Labels: bug, released
